parameters:
    melk.progr.permission.manager.class: Melk\ProgrTeach\MainBundle\Security\PermissionManager

services:
    melk.progr.permission.manager:
        class: %melk.progr.permission.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
