parameters:
#    melk_progr_teach_main.example.class: Melk\ProgrTeach\MainBundle\Example

services:
#    melk_progr_teach_main.example:
#        class: %melk_progr_teach_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
