#app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

melk_progr_teach_main:
    resource: "@MelkProgrTeachMainBundle/Resources/config/routing.yml"
    prefix:   /