Melk\ProgrTeach\MainBundle\Entity\Group:
    type: entity
    table: groups
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        permission:
            targetEntity: Permission
            inversedBy: groups