Melk\ProgrTeach\MainBundle\Entity\Permission:
    type: entity
    table: permissions
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        label:
            type: string
            length: 255
        roles:
            type: json
    oneToMany:
        groups:
            targetEntity: Melk\ProgrTeach\MainBundle\Entity\Group
            mappedBy: permission