Melk\ProgrTeach\MainBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: users_groups
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id